Update install

diff --git a/modules/install b/modules/install
--- a/modules/install
+++ b/modules/install
@@ -1,1 +1,10 @@
 #!/bin/sh
+
+pkg="$1"
+
+if [ ! -d "pkgs/$pkg" ]; then
+    echo "package not found"
+    exit 1
+fi
+
+echo "$pkg was found"
